repos:
- repo: https://github.com/pre-commit/pre-commit-hooks.git
  rev: v4.4.0
  hooks:
    # Git style
    - id: check-added-large-files
    - id: check-merge-conflict
    - id: check-vcs-permalinks
    - id: forbid-new-submodules
    - id: no-commit-to-branch

    # Common errors
    - id: end-of-file-fixer
    - id: trailing-whitespace
      args: ['--markdown-linebreak-ext=md,adoc']
    - id: check-byte-order-marker
    - id: check-yaml
    - id: check-executables-have-shebangs
    - id: check-shebang-scripts-are-executable
    - id: check-symlinks
    - id: destroyed-symlinks

    # Cross platform
    - id: check-case-conflict
    - id: mixed-line-ending
      args: ['--fix=lf']

    # Security
    - id: detect-aws-credentials
      args: ['--allow-missing-credentials']
    - id: detect-private-key

- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.79.1 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
  hooks:
    - id: terraform_fmt
      args:
        - --args=-no-color
        - --args=-diff
        - --args=-write=false



# Terragrunt

- repo: https://github.com/gruntwork-io/pre-commit
  rev: v0.1.17
  hooks:
    - id: terragrunt-hclfmt

#- repo: https://github.com/bridgecrewio/yor.git
#  rev: '0.1.177'
#  hooks:
#    - id: yor
#      name: yor
#      entry: yor tag -d
#      args: [".", "--skip-dirs", ".terragrunt-cache", "--skip-resource-types", "aws_appautoscaling_target" ]
#      language: golang
#      types: [terraform]
#      pass_filenames: false
